### ISSUE TITLE
Listing cosponsors in the API?

### ISSUE THREAD

**Issue by briatte** [teampopong/pokr.kr#50]
Related to #38: is it normal that I don't see the cosponsors of a bill when using the [API](http://data.popong.com/)?

**Comment by briatte** [comment]
Follow-up: I have been scraping your data to build cosponsorship networks.

[Here's a first draft of the graphs](http://f.briatte.org/parlviz/gukhoe/plots.html).

**Comment by e9t** [comment]
Hi @briatte! Sorry for the late reply.
Try out the v0.2 API. (Which is a work in progress, so not on the main page.)

http://data.popong.com/api/v0.2
http://api.popong.com/v0.2/bill/1906357?api_key=test

Great work by the way!

**Comment by briatte** [comment]
Version 0.2 looks great, I'll remember it for future use.
